[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache/**,**/SENTRY-AUTH-TOKEN-FIX.md,**/BUILD-FIXES-APPLIED.md,**/*-FIX.md"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
