name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root dependencies
        run: npm ci
      - name: Install backend dependencies
        run: cd backend && npm ci
      - name: Run frontend tests
        run: npm test -- --coverage --runInBand
      - name: Run backend tests
        run: cd backend && npm test -- --coverage --runInBand
