name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Clear .next directory
        run: rm -rf .next
      - name: Build Next.js app
        run: npm run build
      - name: Verify build output
        run: ls -la .next
      - name: Test start command locally
        run: |
          npm start &
          sleep 5
          curl -f http://localhost:3000 || (echo "Server failed to start" && exit 1)
          pkill -f "npm start" || true
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: false
          parallel: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
